spring.datasource.url=jdbc:postgresql://localhost:5432/oldi_berdi
spring.datasource.username=ilham
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

server.address=0.0.0.0
server.port=9090

file.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB